import { getAsianLanguage } from "@/lib/i18n/languages"
import type { SupportedLanguage } from "@/types"

export type PdfLabels = {
  reportTitle: string
  farmer: string
  crop: string
  date: string
  disease: string
  confidence: string
  severity: string
  cause: string
  symptoms: string
  treatment: string
  prevention: string
  estimatedRecovery: string
  estimatedCost: string
  recoveryOutlook: string
  irrigationNotes: string
  followUp: string
  footer: string
  severityLow: string
  severityMedium: string
  severityHigh: string
}

const LABELS: Partial<Record<SupportedLanguage, PdfLabels>> & { en: PdfLabels } = {
  en: {
    reportTitle: "Crop Diagnosis Report",
    farmer: "Farmer",
    crop: "Crop",
    date: "Date",
    disease: "Disease",
    confidence: "Confidence",
    severity: "Severity",
    cause: "Cause",
    symptoms: "Symptoms",
    treatment: "Treatment plan",
    prevention: "Prevention",
    estimatedRecovery: "Estimated recovery",
    estimatedCost: "Estimated cost (LKR)",
    recoveryOutlook: "Recovery outlook",
    irrigationNotes: "Irrigation notes",
    followUp: "Follow-up",
    footer:
      "Generated by AgriMind AI — Your AI Farming Partner From Seed To Harvest.",
    severityLow: "LOW",
    severityMedium: "MEDIUM",
    severityHigh: "HIGH",
  },
  si: {
    reportTitle: "බෝග රෝග විනිශ්චය වාර්තාව",
    farmer: "ගොවියා",
    crop: "බෝගය",
    date: "දිනය",
    disease: "රෝගය",
    confidence: "විශ්වාසය",
    severity: "දැඩි බව",
    cause: "හේතුව",
    symptoms: "ලක්ෂණ",
    treatment: "ප්‍රතිකාර සැලසුම",
    prevention: "ප්‍රතිරෝධය",
    estimatedRecovery: "ඇස්තමේන්තු සුව කාලය",
    estimatedCost: "ඇස්තමේන්තු වියදම (රු.)",
    recoveryOutlook: "සුව පිළිබඳ දළ විශ්ලේෂණය",
    irrigationNotes: "වාරිමාර්ග සටහන්",
    followUp: "අනුගමනය",
    footer:
      "AgriMind AI මගින් සකසන ලදී — බීජයේ සිට අස්වැන්න දක්වා ඔබේ AI කෘෂිකර්ම සහකාර.",
    severityLow: "අඩු",
    severityMedium: "මධ්‍යම",
    severityHigh: "ඉහළ",
  },
  ta: {
    reportTitle: "பயிர் நோய் கண்டறிதல் அறிக்கை",
    farmer: "விவசாயி",
    crop: "பயிர்",
    date: "தேதி",
    disease: "நோய்",
    confidence: "நம்பகத்தன்மை",
    severity: "தீவிரம்",
    cause: "காரணம்",
    symptoms: "அறிகுறிகள்",
    treatment: "சிகிச்சை திட்டம்",
    prevention: "தடுப்பு",
    estimatedRecovery: "மதிப்பிடப்பட்ட குணமடைதல்",
    estimatedCost: "மதிப்பிடப்பட்ட செலவு (ரூ.)",
    recoveryOutlook: "குணமடைதல் கண்ணோட்டம்",
    irrigationNotes: "பாசன குறிப்புகள்",
    followUp: "பின்தொடர்தல்",
    footer:
      "AgriMind AI உருவாக்கியது — விதை முதல் அறுவடை வரை உங்கள் AI விவசாய துணை.",
    severityLow: "குறைவு",
    severityMedium: "நடுத்தர",
    severityHigh: "அதிக",
  },
  hi: {
    reportTitle: "फसल रोग निदान रिपोर्ट",
    farmer: "किसान",
    crop: "फसल",
    date: "तारीख",
    disease: "रोग",
    confidence: "विश्वास",
    severity: "गंभीरता",
    cause: "कारण",
    symptoms: "लक्षण",
    treatment: "उपचार योजना",
    prevention: "रोकथाम",
    estimatedRecovery: "अनुमानित स्वस्थ होने का समय",
    estimatedCost: "अनुमानित लागत (रु.)",
    recoveryOutlook: "स्वस्थ होने की संभावना",
    irrigationNotes: "सिंचाई नोट्स",
    followUp: "अनुवर्ती",
    footer:
      "AgriMind AI द्वारा बनाई गई — बीज से फसल तक आपका AI कृषि साथी।",
    severityLow: "कम",
    severityMedium: "मध्यम",
    severityHigh: "अधिक",
  },
}

export function getPdfLabels(lang: SupportedLanguage): PdfLabels {
  return LABELS[lang] ?? LABELS.en
}

export function formatPdfDate(date: Date, lang: SupportedLanguage): string {
  const bcp47 = getAsianLanguage(lang)?.bcp47 ?? "en-LK"
  try {
    return date.toLocaleDateString(bcp47, {
      year: "numeric",
      month: "long",
      day: "numeric",
    })
  } catch {
    return date.toLocaleDateString("en-LK")
  }
}

export function severityLabel(
  severity: string,
  labels: PdfLabels
): string {
  const key = severity.toLowerCase()
  if (key === "low") return labels.severityLow
  if (key === "medium") return labels.severityMedium
  if (key === "high") return labels.severityHigh
  return severity.toUpperCase()
}
