import { jsPDF } from "jspdf"
import { getAgriMindLogoDataUrl } from "@/lib/brand/logo-pdf"
import type { CropDiagnosisResult } from "@/types/ai"

const HEADER_HEIGHT_MM = 32
const LOGO_SIZE_MM = 18

export interface DiagnosisPdfInput {
  farmerName: string
  cropType: string
  createdAt: Date
  diagnosis: CropDiagnosisResult
  imageUrl?: string
}

export function generateDiagnosisPdf(input: DiagnosisPdfInput): Buffer {
  const doc = new jsPDF({ unit: "mm", format: "a4" })
  const { diagnosis: d } = input
  let y = 18

  const line = (text: string, size = 11, bold = false) => {
    doc.setFontSize(size)
    doc.setFont("helvetica", bold ? "bold" : "normal")
    const lines = doc.splitTextToSize(text, 180)
    if (y + lines.length * 6 > 280) {
      doc.addPage()
      y = 18
    }
    doc.text(lines, 15, y)
    y += lines.length * 6 + 2
  }

  doc.setFillColor(34, 120, 70)
  doc.rect(0, 0, 210, HEADER_HEIGHT_MM, "F")

  const logo = getAgriMindLogoDataUrl()
  const titleX = logo ? 14 + LOGO_SIZE_MM + 5 : 15
  const logoY = (HEADER_HEIGHT_MM - LOGO_SIZE_MM) / 2

  if (logo) {
    doc.addImage(logo, "PNG", 14, logoY, LOGO_SIZE_MM, LOGO_SIZE_MM)
  }

  doc.setTextColor(255, 255, 255)
  doc.setFontSize(16)
  doc.setFont("helvetica", "bold")
  doc.text("AgriMind AI", titleX, 14)
  doc.setFontSize(11)
  doc.setFont("helvetica", "normal")
  doc.text("Crop Diagnosis Report", titleX, 22)

  doc.setTextColor(30, 30, 30)
  y = HEADER_HEIGHT_MM + 10

  line(`Farmer: ${input.farmerName}`, 11, true)
  line(`Crop: ${input.cropType}  |  Date: ${input.createdAt.toLocaleDateString("en-LK")}`)
  line(`Disease: ${d.disease}`, 13, true)
  line(`Confidence: ${d.confidence}%  |  Severity: ${d.severity.toUpperCase()}`)
  y += 4

  line("Cause", 12, true)
  line(d.cause)
  line("Symptoms", 12, true)
  d.symptoms.forEach((s) => line(`• ${s}`))

  line("Treatment plan", 12, true)
  d.treatment.forEach((t) => {
    line(`${t.step}. ${t.action} (${t.timing})`, 11, true)
    if (t.details) line(t.details)
  })

  line("Prevention", 12, true)
  d.prevention.forEach((p) => line(`• ${p}`))

  line("Estimated recovery", 12, true)
  line(d.estimatedRecovery)
  line("Estimated cost (LKR)", 12, true)
  line(d.costEstimate)
  if (d.recoverySummary) {
    line("Recovery outlook", 12, true)
    line(d.recoverySummary)
  }
  if (d.irrigationNotes) {
    line("Irrigation notes", 12, true)
    line(d.irrigationNotes)
  }
  if (d.followUpAdvice) {
    line("Follow-up", 12, true)
    line(d.followUpAdvice)
  }

  y += 6
  doc.setFontSize(9)
  doc.setTextColor(120, 120, 120)
  doc.text(
    "Generated by AgriMind AI — Your AI Farming Partner From Seed To Harvest.",
    15,
    285
  )

  const arrayBuffer = doc.output("arraybuffer")
  return Buffer.from(arrayBuffer)
}
